version: '3'

services:
  

  postgres:
    image: postgres:14.3
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - apiservice
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

  core:
    build:
      context: ./core
    container_name: core
    ports:
      - 8000:8000
    volumes:
      - ./core:/core
    working_dir: /core
    command: python manage.py runserver 0:8000
    environment:
      - API_ENTRYPOINT=http://postgres:5432/graphql
    depends_on:
      - postgres
    networks:
      - apiservice
networks:
  apiservice:

volumes:
  pgdata:
